### PR TITLE
Replaced Soomla prefabs with CodeGeneratedSingleton

### PR DESCRIPTION
**Pull request by LeshM**
Introduced Round Robin's "UnitySingleton", thus making the different Soomla prefabs redundant

### CODE REVIEW

**Comment by vedi** [comment]
@LeshM, how is it supposed to work for developers? 
Should they just skip the step: "Drag the "StoreEvents" and "CoreEvents" Prefabs from Assets/Soomla/Prefabs into your scene."?

I have the errors:
```
Assets/Plugins/Soomla/Core/Singletons/UnitySingleton.cs(55,47): error CS1061: Type `UnityEngine.Object' does not contain a definition for `GetComponent' and no extension method `GetComponent' of type `UnityEngine.Object' could be found (are you missing a using directive or an assembly reference?)
Assets/Plugins/Soomla/Core/Singletons/UnitySingleton.cs(59,51): error CS1061: Type `UnityEngine.Object' does not contain a definition for `AddComponent' and no extension method `AddComponent' of type `UnityEngine.Object' could be found (are you missing a using directive or an assembly reference?)
```
But I'm on Unity3d v4.6. Is it supported? Maybe I do something wrong?

**Comment by refaelos** [comment]
@vedi did you import "GameObject" ?

**Comment by LeshM** [comment]
I'll check it out again on Unity 4.6 and the new 5.2 to make sure it works on all versions.

**Comment by LeshM** [comment]
Sorry, my bad.
All fixed and ready to pull :)

**Pull request merged**
